### ISSUE TITLE
TODO list for 1.0.0

### ISSUE THREAD

**Issue by semiversus** [semiversus/python-broqer#17]
- [x] support unary operators for publishers (`len()`, `str()`, `int()`, `-`, ...)
- [x] complete tests of operators
- [x] make op.Trace actually useful for debugging
- [x] add missing datatypes for datatype check
- [x] unify argument names: `func`, `function`, `callback`, `map_func`
- [x] always apply partial to simplify code
- [x] move TopicMapper and DTRegistry to broqer.hub.utils
